package ClassEnergie.Enum;

public enum Pays {
    // indetifer chaque pays avec un identifiant unique
    FRANCE("FRANCE"), // 000
    ALBANIE("ALBANIE"), // 001
    ALGERIE("ALGERIE"), // 002
    ALLEMAGNE("ALLEMAGNE"), // 003
    ANGOLA("ANGOLA"), // 004
    ARMENIE("ARMENIE"), // 005
    AUSTRALIE("AUSTRALIE"), // 006
    AUTRICHE("AUTRICHE"), // 007
    AZERBAIDJAN("AZERBAIDJAN"), // 008
    BANGLADESH("BANGLADESH"), // 009
    BELGIQUE("BELGIQUE"), // 010
    BENIN("BENIN"), // 011
    BIRMANIE("BIRMANIE"), // 012
    BOSNIE("BOSNIE"), // 013
    BULGARIE("BULGARIE"), // 014
    BULGARIE_DU_NORD("BULGARIE_DU_NORD"), // 015
    BURUNDI("BURUNDI"), // 016
    CAMEROUN("CAMEROUN"), // 017
    CANADA("CANADA"), // 018
    CENTRAFRIQUE("CENTRAFRIQUE"), // 019
    CHAD("CHAD"), // 020
    CHINE("CHINE"), // 021
    CONGO("CONGO"), // 022
    COREE_DU_SUD("COREE_DU_SUD"), // 023
    COSTA_RICA("COSTA_RICA"), // 024
    COTE_D_IVOIRE("COTE_D_IVOIRE"), // 025
    CROATIE("CROATIE"), // 026
    CUBA("CUBA"), // 027
    DANEMARK("DANEMARK"), // 028
    DJIBOUTI("DJIBOUTI"), // 029
    DOMINICAINE("DOMINICAINE"), // 030
    ERYTHREE("ERYTHREE"), // 031
    ESPAGNE("ESPAGNE"), // 032
    ESTONIE("ESTONIE"), // 033
    ETATS_UNIS("ETATS_UNIS"), // 034
    ETIOPIE("ETIOPIE"), // 035
    FINLANDE("FINLANDE"), // 036
    GABON("GABON"), // 037
    GAMBIE("GAMBIE"), // 038
    GEORGIE("GEORGIE"), // 039
    GHANA("GHANA"), // 040
    GRECE("GRECE"), // 041
    GRECE_DU_NORD("GRECE_DU_NORD"), // 042
    GUATEMALA("GUATEMALA"), // 043
    GUINEE("GUINEE"), // 044
    GUINEE_EQUATORIALE("GUINEE_EQUATORIALE"), // 045
    HAITI("HAITI"), // 046
    HONDURAS("HONDURAS"), // 047
    HONGRIE("HONGRIE"), // 048
    INDE("INDE"), // 049
    INDONESIE("INDONESIE"), // 050
    ITALIE("ITALIE"), // 051
    JAPON("JAPON"), // 052
    KENYA("KENYA"), // 053
    LAOS("LAOS"), // 054
    LETTONIE("LETTONIE"), // 055
    LIBYE("LIBYE"), // 056
    LITUANIE("LITUANIE"), // 057
    MACEDOINE("MACEDOINE"), // 058
    MACEDOINE_DU_NORD("MACEDOINE_DU_NORD"), // 059
    MALAISIE("MALAISIE"), // 060
    MAROC("MAROC"), // 061
    MAURITANIE("MAURITANIE"), // 062
    MEXIQUE("MEXIQUE"), // 063
    MOLDAVIE("MOLDAVIE"), // 064
    MONTENEGRO("MONTENEGRO"), // 065
    MOZAMBIQUE("MOZAMBIQUE"), // 066
    NEPAL("NEPAL"), // 067
    NICARAGUA("NICARAGUA"), // 068
    NIGER("NIGER"), // 069
    NIGERIA("NIGERIA"), // 070
    NORVEGE("NORVEGE"), // 071
    NOUVELLE_ZELANDE("NOUVELLE_ZELANDE"), // 072
    OUGANDA("OUGANDA"), // 073
    PANAMA("PANAMA"), // 074
    PAYS_BAS("PAYS_BAS"), // 075
    PHILIPPINES("PHILIPPINES"), // 076
    POLOGNE("POLOGNE"), // 077
    PORTUGAL("PORTUGAL"), // 078
    REPUBLIQUE_CENTRAFRICAINE("REPUBLIQUE_CENTRAFRICAINE"), // 079
    REPUBLIQUE_DEMOGRAPHIQUE_DU_CONGO("REPUBLIQUE_DEMOGRAPHIQUE_DU_CONGO"), // 080
    REPUBLIQUE_TCHEQUE("REPUBLIQUE_TCHEQUE"), // 081
    ROUMANIE("ROUMANIE"), // 082
    RWANDA("RWANDA"), // 083
    SALVADOR("SALVADOR"), // 084
    SENEGAL("SENEGAL"), // 085
    SERBIE("SERBIE"), // 086
    SINGAPOUR("SINGAPOUR"), // 087
    SLOVAQUIE("SLOVAQUIE"), // 088
    SLOVENIE("SLOVENIE"), // 089
    SOMALIE("SOMALIE"), // 090
    SUDAN("SUDAN"), // 091
    SUEDDE("SUEDDE"), // 092
    SUISSE("SUISSE"), // 093
    TANZANIE("TANZANIE"), // 094
    TCHECOSLOVAQUIE("TCHECOSLOVAQUIE"), // 095
    THAILANDE("THAILANDE"), // 096
    TOGO("TOGO"), // 097
    TUNISIE("TUNISIE"), // 098
    TURQUIE("TURQUIE"), // 099
    UKRAINE("UKRAINE"), // 100
    VIETNAM("VIETNAM"), // 101
    ZAMBIE("ZAMBIE"), // 102
    ZIMBABWE("ZIMBABWE"); // 103

    private String nom;

    Pays(String nom) {
        this.nom = nom;
    }

    public String toString() {
        return nom;
    }

    public static Pays getValue(String s) {
        s = s.toUpperCase();
        for (Pays p : Pays.values()) {
            if (p.nom.equals(s))
                return p;
        }
        return null;
    }
}